"""make role model name unique

Revision ID: 3ed7392eb7ad
Revises: 3fcd9940bfe5
Create Date: 2026-08-13 04:22:04.366088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed7392eb7ad'
down_revision: Union[str, Sequence[str], None] = '3fcd9940bfe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role_models', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_models', type_='unique')
    # ### end Alembic commands ###
