"""Add career_stage to users

Revision ID: 3fcd9940bfe5
Revises: f9d2026d51d5
Create Date: 2026-08-07 04:40:10.415274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcd9940bfe5'
down_revision: Union[str, Sequence[str], None] = 'f9d2026d51d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('career_stage', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'career_stage')
    # ### end Alembic commands ###
