"""cascade delete auth codes with user

Revision ID: a37ec94f2805
Revises: 70356a8a2534
Create Date: 2026-08-21 08:31:56.005881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37ec94f2805'
down_revision: Union[str, Sequence[str], None] = '70356a8a2534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_codes_user_id_fkey'), 'auth_codes', type_='foreignkey')
    op.create_foreign_key(None, 'auth_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_codes', type_='foreignkey')
    op.create_foreign_key(op.f('auth_codes_user_id_fkey'), 'auth_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
